apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: felipearredond/telematica:version3
          ports:
            - containerPort: 9091
          env:
            - name : GRPC_SERVER_PORT
              value: "9091"
---

apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  selector:
    app: grpc-server
  type: ClusterIP       
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091

