server:
  port: 8080
spring:
  application:
    name: ms_server
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:filesdb
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
grpc:
  server:
    port: 9091