server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:filesdb
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
service:
  grpc:
    peerName: ${PEER_NAME:grpc-peer-1}
    neighbor: ${NEIGHBOR_NAME:grpc-peer-2}
    host: ${GRPC_HOST:localhost}
grpc:
  server:
    port: 9091